# Generated by Django 6.0.7 on 2026-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('to do', 'TO DO'), ('in progress', 'IN PROGRESS'), ('in code review', 'IN CODE REVIEW'), ('blocked dev', 'BLOCKED (DEV)'), ('ready for test', 'READY FOR TEST'), ('in test', 'IN TEST'), ('blocked test', 'BLOCKED (TEST)'), ('done', 'DONE')], default='to do', max_length=30),
        ),
    ]
