# Generated by Django 6.0.7 on 2026-07-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Tahmini süre (saat)'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Acil')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('task', 'Görev'), ('bug', 'Hata'), ('story', 'Hikaye'), ('epic', 'Epic')], default='task', max_length=20),
        ),
    ]
