# Generated by Django 6.0.7 on 2026-07-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_due_date_task_duration_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='epic',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
