# Generated by Django 6.0.7 on 2026-07-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_user_otp_code_user_otp_created_at_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
